server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cassandra:
    keyspace-name: chat4all
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1 # <--- Esta linha Ã© a chave para corrigir o erro
    schema-action: CREATE_IF_NOT_EXISTS

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: chat-files