global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'chat4all_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # API Frontend
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'frontend-service'
      
      # Worker 1 (Líder - Padrão)
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'router-worker'
          instance_id: 'worker-1'

      # Worker 2 (Ajudante - Porta Extra)
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'router-worker'
          instance_id: 'worker-2'

      # Worker 3 (Estagiário - Porta Extra)
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'router-worker'
          instance_id: 'worker-3'

      # WhatsApp Mock
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'connector-whatsapp'

      # Instagram Mock
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'connector-instagram'